theme: jekyll-theme-slate
title: Sorbus
description: SCSS Auto-Theme for the Rouge Higlighter.
show_downloads: true
license:
  name: MIT
  url: https://github.com/BenSouchet/sorbus/blob/main/LICENSE
maintainers:
  - name: Ben Souchet
    url: https://github.com/BenSouchet
